server:
  port: 8123
  servlet:
    context-path: /api

spring:
  application:
    name: yuan-picture-backend
    # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuan_picture
    username: root
    password: 961213

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-field: isDeleted
      # 1 表示已删除，0 表示未删除
      logic-delete-value: 1
      logic-not-delete-value: 0

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: yuan官方文档
    version: v1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.wzy.yuanpicturebackend.controller